swagger: '2.0'
info:
  title: gwabfunctions.azurewebsites.net
  version: 1.0.0
host: gwabfunctions.azurewebsites.net
basePath: /
schemes:
  - https
paths:
  /api/hello:
    get:
      operationId: /api/hello/get
      produces:
        - string
      consumes:
        - string
      parameters:
        - name: name
          in: query
          description: Your name
          required: true
          type: string
      description: >-
        Replace with Operation Object
        #http://swagger.io/specification/#operationObject
      responses:
        '200':
          description: Success operation
      security:
        - apikeyQuery: []
definitions: {}
securityDefinitions:
  apikeyQuery:
    type: apiKey
    name: code
    in: query
